apiVersion: v1
kind: ConfigMap
metadata:
  name: shoppilot-config
  namespace: shoppilot
  labels:
    app: shoppilot
    component: config
data:
  PORT: "5000"
  JWT_EXPIRE: "30d"
  REACT_APP_API_URL: "http://localhost:30001/api" # Assume NodePort mapping, or LB IP later
  VITE_API_URL: "http://localhost:30001/api"
