apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: shoppilot
  labels:
    app: shoppilot
    component: frontend
spec:
  type: LoadBalancer # k3s uses traefik/svclb for LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30002
  selector:
    app: shoppilot
    component: frontend
